import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import AdvancedDayjsFormat from "dayjs/plugin/advancedFormat";
import dayjs from "dayjs";
import "./globals.css";
import { ReactQueryPorvider } from "@/components/ReactQueryProvider";

dayjs.extend(AdvancedDayjsFormat);
const poppins_init = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Resume Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins_init.className} antialiased`}>
        <ReactQueryPorvider>
          <AntdRegistry>{children}</AntdRegistry>
        </ReactQueryPorvider>
      </body>
    </html>
  );
}
